### ISSUE TITLE
App Crash after the recent package resolve

### ISSUE THREAD

**Issue by Nookaraju** [LottieFiles/dotlottie-ios#13]
<img width="1444" alt="Screenshot 2024-02-09 at 1 17 33 AM" src="https://github.com/LottieFiles/dotlottie-ios/assets/2161122/0012548f-720d-45d5-bda9-f7ef49f23db8">

**Comment by samuelOsborne** [comment]
hey @Nookaraju it might be due to the layer effect being not supported as per the console logs, could you share the animation with me please?

**Comment by Nookaraju** [comment]
[Infor_END TAG_NoGrid.json](https://github.com/LottieFiles/dotlottie-ios/files/14219926/Infor_END.TAG_NoGrid.json)

**Comment by samuelOsborne** [comment]
@Nookaraju Could you show your view code please, how you're displaying the animation

also does it crash on every launch or occasionally?

**Comment by Nookaraju** [comment]
var simpleVM = DotLottieAnimation(fileName: "Infor_END TAG_NoGrid", config:AnimationConfig(autoplay: true, loop: true))
let loaderView: DotLottieAnimationView = simpleVM.view()
loaderView.translatesAutoresizingMaskIntoConstraints = false
animateView.addSubview(loaderView)
MGUtil.anchorSubView(loaderView, toOccupySuperView: animateView, withInset: UIEdgeInsets.zero)

Every launch, it is crashing.

**Comment by samuelOsborne** [comment]
hi @Nookaraju I used your way of instantiating the player and its running, except that I didnt use 

```
MGUtil.anchorSubView(loaderView, toOccupySuperView: animateView, withInset: UIEdgeInsets.zero)
```

and used instead

```
        loaderView.frame = view.bounds
```

Would you be able to share your animation? If possible a full reproducible snippet would be great too please
