### ISSUE TITLE
The player is created every time

### ISSUE THREAD

**Issue by IvanZakharov16** [LottieFiles/dotlottie-ios#14]
Good afternoon,
Thanks for a great library!

Every time I push View with DotLottieView, a player(Player, DotLottiePlayer) is created each time and is not deleted from memory when I dismiss the View.

It works even with a simple View like:
import SwiftUI
import DotLottie

struct LottieAnimationSwiftView: View {
    var body: some View {
        VStack {
            DotLottieAnimation(fileName: "lsingb0d", config: AnimationConfig(autoplay: true, loop: true)).view()
        }
    }
}

Please tell me how to fix this.

![Screenshot 2024-02-12 at 14 11 39](https://github.com/LottieFiles/dotlottie-ios/assets/144654944/bf2ad07a-2d1a-4f71-a56f-689c720919ee)

**Comment by samuelOsborne** [comment]
hi @IvanZakharov16 Will look in to this can get back to you shortly

**Comment by IvanZakharov16** [comment]
thanks for the help! now it works great, but i noticed other memory leaks. I think they're somewhere in C code.
![Screenshot 2024-03-05 at 11 27 30](https://github.com/LottieFiles/dotlottie-ios/assets/144654944/e233032e-a806-4434-af37-50e6e0b7ca1d)

**Comment by samuelOsborne** [comment]
Yes @IvanZakharov16 Its a WIP to remove all the leaks, under the hood we have a rust player using a c++ renderer. For the moment as this issue has been fixed I'll close it but we're working to get rid of these leaks soon! :)
