### ISSUE TITLE
Wrong minimum OS Version on binary target

### ISSUE THREAD

**Issue by tuannguyenanh177** [LottieFiles/dotlottie-ios#16]
Hello,

I can not upload my app to AppStore due invalid minimum OS Version in binary target. I tried change this value to 13.0 however it doesn't work. Could you please help check on this issue?

My project iOS target: 15.0

<img width="790" alt="Screenshot 2024-02-22 at 9 58 55 PM" src="https://github.com/LottieFiles/dotlottie-ios/assets/16713961/781edcb7-99f9-4cc5-b36b-0e078e169670">

<img width="832" alt="Screenshot 2024-02-22 at 10 02 08 PM" src="https://github.com/LottieFiles/dotlottie-ios/assets/16713961/4b41be9f-e1d2-490f-8f93-4b4a00766c97">

**Comment by samuelOsborne** [comment]
hi @tuannguyenanh177 I'm going to investigate and get back to you shortly

**Comment by samuelOsborne** [comment]
hi @tuannguyenanh177 Please try with v0.2.2 of the player

**Comment by PollyVern** [comment]
Good afternoon. I have the same situation as the previous comments. Is there a solution to this problem?
![photo_2024-04-12 15 20 59](https://github.com/LottieFiles/dotlottie-ios/assets/68129686/b131084c-d0b2-4ce7-94ac-4135cd64a1d6)

**Comment by PollyVern** [comment]
Good afternoon, @samuelOsborne . I have the same situation as the previous comments. Is there a solution to fix this problem?
![photo_2024-04-12 15 20 59](https://github.com/LottieFiles/dotlottie-ios/assets/68129686/99bd5b38-d338-4aae-a3e7-8be7d43c06fe)

**Comment by PollyVern** [comment]
@samuelOsborne Minimum OS version in project - 14.0

**Comment by samuelOsborne** [comment]
hi @PollyVern I think ive located the problem. Inside our plist files the min version is 13.0 but the binaries have it set to 17.0

Currently investigating why this is happening

**Comment by samuelOsborne** [comment]
hi @PollyVern thanks for your patience, atm the early minimum os version I can get to is 15.5 via our github ci/cd build pipeline

Im gonna to try and build the core player locally with lower ios sdks if I manage to get them out of xcode

**Comment by PollyVern** [comment]
@samuelOsborne Thank you so much for quickly trying to rectify the situation. Sure wish you could find a solution, because we won't be able to get the project version up to 15.5.
I look forward to any changes

**Comment by samuelOsborne** [comment]
hi @PollyVern @tuannguyenanh177. After updating our workflow, the lowest SDK version i've managed to use for iOS is 15.4, you can find the release here ➡️ https://github.com/LottieFiles/dotlottie-ios/releases/tag/v0.4.1

I know you both wanted lower versions, but for the moment this is the lowest our github runners will allow without breaking :(

**Comment by PollyVern** [comment]
@samuelOsborne  Thank you for trying to solve the problem. On the current project, alas, I will just use the "Lottie" library

**Comment by badepaz** [comment]
![2f74fa8d-7c69-4b63-a45a-9a7f9ee2c159](https://github.com/LottieFiles/dotlottie-ios/assets/18727848/d901225d-b0d2-41d1-bb28-22180981f3c8)

I'm having the same issue here. And _my_ project's iOS minimum version is iOS 16.

**Comment by badepaz** [comment]
I'm having the same issue. And my project's iOS minimum version is set to iOS 16.

![screenshot](https://github.com/LottieFiles/dotlottie-ios/assets/18727848/77a5f35a-63c3-4354-ab65-43ca74b26632)

**Comment by samuelOsborne** [comment]
hi @badepaz sorry about that, will continue looking in to it and let you know

**Comment by samuelOsborne** [comment]
hi @badepaz Please try out the [latest](https://github.com/LottieFiles/dotlottie-ios/releases/tag/v0.6.1) release of dotlottie-ios for the fix!

cheers
