### ISSUE TITLE
Unable to load animations from the web. 

### ISSUE THREAD

**Issue by bks715** [LottieFiles/dotlottie-ios#25]
Get a fatal error when trying to use animations from the web. 

Thread 3: EXC_BREAKPOINT (code=1, subcode=0x102f9a490)

`public func loadDotlottieData(fileData: Data, width: UInt32, height: UInt32) -> Bool {
        return try! FfiConverterBool.lift(
            try!
                rustCall {
                    uniffi_dotlottie_player_fn_method_dotlottieplayer_load_dotlottie_data(self.uniffiClonePointer(),
                                                                                          FfiConverterData.lower(fileData),
                                                                                          FfiConverterUInt32.lower(width),
                                                                                          FfiConverterUInt32.lower(height), $0)
                }
        )
    }`

**Comment by samuelOsborne** [comment]
@bks715 can you please share your implementation code.
